[workspace]
resolver = "3"
members = ["not_vim", "not_vim_terminal"]

[workspace.dependencies]
crossterm = "0.27"
gag = "1"
anyhow = "1"
bitflags = "2"
ropey = "1.6.0"

[profile.opt]
inherits = "release"
lto = true
codegen-units = 1
opt-level = 3
strip = true
